name: Talk to chatbot jarvis
on:
    workflow_dispatch:
    workflow_call:
jobs:
    chatbot-command-dispatch:
        runs-on: [ubuntu-latest]
        steps:
            - name: Talk to Chatbot jarvis
              uses: peter-evans/slash-command-dispatch@v3
              with:
                  token: ${{ secrets.ACTIONS_BOT_TOKEN }}
                  reaction-token: ${{ secrets.ACTIONS_BOT_TOKEN }}
                  repository: Mason-Lin/jarvis
                  commands: jarvis
