name: PR Code Fixer

on:
    workflow_dispatch:
    workflow_call:

jobs:
    pr-code-fixer:
        if: "!startsWith(github.head_ref, 'dependabot/')"
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.9"

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Run pre-commit autofix
              run: pre-commit run --all-files || echo "changed"

            - name: Uninstall pre-commit
              run: pre-commit uninstall

            - name: Commit Changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 🐛 Auto-fix pre-commit hooks
                  commit_user_name: Mason Lin
                  commit_user_email: pizza0117@gmail.com
                  commit_author: Mason Lin <pizza0117@gmail.com>

    docker-build-checks:
        if: "!startsWith(github.head_ref, 'dependabot/')"
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v4

            - name: Linter
              run: docker build --target=dev-linter -t docker_name:dev-linter .

            - name: Coverage
              run: docker build --target=dev-coverage -t docker_name:dev-coverage .

            - name: Security
              run: docker build --target=dev-security -t docker_name:dev-security .

    code-spell-checker:
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.9"

            - name: Install codespell
              run: pip install codespell tomli

            - name: Run codespell
              run: |
                  codespell \
                  --check-filenames \
                  --builtin clear,rare,informal,code,names,en-GB_to_en-US \
                  src/ README.md
